[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/.well-known/assetlinks.json"
  [headers.values]
    Content-Type = "application/json"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/json"

[[headers]]
  for = "/service-worker.js"
  [headers.values]
    Content-Type = "application/javascript"
    Service-Worker-Allowed = "/"

[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
